<?php

namespace Sofid\AdminBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class OffreController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sofid\AdminBundle\Controller\OffreController();
        return $instance;
    }
}
