<?php

namespace Proxies\__CG__\Sofid\UserBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Commercant extends \Sofid\UserBundle\Entity\Commercant implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'image', 'picture', 'firstname', 'lastname', 'dateOfBirth', 'client', 'sms', 'category', 'ticketMoyen', 'ticketEphemMoyen', 'website', 'facebookPage', 'gender', 'phone', 'password', 'nbPointScan', 'shares', 'entreprise', 'editable', 'display_editable', 'exportOption', 'MessageManualPointsScreen', 'limitpoints1', 'limitpoints2', 'raisonSociale', 'adresse', 'conversionValue', 'codePostal', 'ville', 'pays', 'code', 'paliers', 'offres', 'gains', 'timeSpentLogs', 'transactions', 'questions', 'temp', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
        }

        return array('__isInitialized__', 'id', 'image', 'picture', 'firstname', 'lastname', 'dateOfBirth', 'client', 'sms', 'category', 'ticketMoyen', 'ticketEphemMoyen', 'website', 'facebookPage', 'gender', 'phone', 'password', 'nbPointScan', 'shares', 'entreprise', 'editable', 'display_editable', 'exportOption', 'MessageManualPointsScreen', 'limitpoints1', 'limitpoints2', 'raisonSociale', 'adresse', 'conversionValue', 'codePostal', 'ville', 'pays', 'code', 'paliers', 'offres', 'gains', 'timeSpentLogs', 'transactions', 'questions', 'temp', 'username', 'usernameCanonical', 'email', 'emailCanonical', 'enabled', 'salt', 'plainPassword', 'lastLogin', 'confirmationToken', 'passwordRequestedAt', 'groups', 'locked', 'expired', 'expiresAt', 'roles', 'credentialsExpired', 'credentialsExpireAt');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Commercant $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getFullname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullname', array());

        return parent::getFullname();
    }

    /**
     * {@inheritDoc}
     */
    public function isEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEditable', array());

        return parent::isEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setEditable($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEditable', array($boolean));

        return parent::setEditable($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEntreprise($entreprise)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntreprise', array($entreprise));

        return parent::setEntreprise($entreprise);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntreprise()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntreprise', array());

        return parent::getEntreprise();
    }

    /**
     * {@inheritDoc}
     */
    public function setRaisonSociale($raisonSociale)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRaisonSociale', array($raisonSociale));

        return parent::setRaisonSociale($raisonSociale);
    }

    /**
     * {@inheritDoc}
     */
    public function getRaisonSociale()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRaisonSociale', array());

        return parent::getRaisonSociale();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostal($codePostal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostal', array($codePostal));

        return parent::setCodePostal($codePostal);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostal', array());

        return parent::getCodePostal();
    }

    /**
     * {@inheritDoc}
     */
    public function setVille($ville)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVille', array($ville));

        return parent::setVille($ville);
    }

    /**
     * {@inheritDoc}
     */
    public function getVille()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVille', array());

        return parent::getVille();
    }

    /**
     * {@inheritDoc}
     */
    public function setPays($pays)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPays', array($pays));

        return parent::setPays($pays);
    }

    /**
     * {@inheritDoc}
     */
    public function getPays()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPays', array());

        return parent::getPays();
    }

    /**
     * {@inheritDoc}
     */
    public function addPalier(\Sofid\AdminBundle\Entity\Palier $paliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPalier', array($paliers));

        return parent::addPalier($paliers);
    }

    /**
     * {@inheritDoc}
     */
    public function removePalier(\Sofid\AdminBundle\Entity\Palier $paliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePalier', array($paliers));

        return parent::removePalier($paliers);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaliers()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaliers', array());

        return parent::getPaliers();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaliers($paliers)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaliers', array($paliers));

        return parent::setPaliers($paliers);
    }

    /**
     * {@inheritDoc}
     */
    public function addOffre(\Sofid\AdminBundle\Entity\Offre $offres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOffre', array($offres));

        return parent::addOffre($offres);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOffre(\Sofid\AdminBundle\Entity\Offre $offres)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOffre', array($offres));

        return parent::removeOffre($offres);
    }

    /**
     * {@inheritDoc}
     */
    public function getOffres()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOffres', array());

        return parent::getOffres();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function addGain(\Sofid\AdminBundle\Entity\Gain $gains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGain', array($gains));

        return parent::addGain($gains);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGain(\Sofid\AdminBundle\Entity\Gain $gains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGain', array($gains));

        return parent::removeGain($gains);
    }

    /**
     * {@inheritDoc}
     */
    public function getGains()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGains', array());

        return parent::getGains();
    }

    /**
     * {@inheritDoc}
     */
    public function setGains($gains)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGains', array($gains));

        return parent::setGains($gains);
    }

    /**
     * {@inheritDoc}
     */
    public function addTimeSpentLog(\Sofid\AdminBundle\Entity\TimeSpentLog $timeSpentLogs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTimeSpentLog', array($timeSpentLogs));

        return parent::addTimeSpentLog($timeSpentLogs);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTimeSpentLog(\Sofid\AdminBundle\Entity\TimeSpentLog $timeSpentLogs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTimeSpentLog', array($timeSpentLogs));

        return parent::removeTimeSpentLog($timeSpentLogs);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeSpentLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeSpentLog', array());

        return parent::getTimeSpentLog();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeSpentLog($timeSpentLogs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeSpentLog', array($timeSpentLogs));

        return parent::setTimeSpentLog($timeSpentLogs);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncoderName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncoderName', array());

        return parent::getEncoderName();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPointScan($nbPointScan)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPointScan', array($nbPointScan));

        return parent::setNbPointScan($nbPointScan);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPointScan()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPointScan', array());

        return parent::getNbPointScan();
    }

    /**
     * {@inheritDoc}
     */
    public function setShares($shares)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShares', array($shares));

        return parent::setShares($shares);
    }

    /**
     * {@inheritDoc}
     */
    public function getShares()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShares', array());

        return parent::getShares();
    }

    /**
     * {@inheritDoc}
     */
    public function addTransaction(\Sofid\AdminBundle\Entity\Transaction $transactions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTransaction', array($transactions));

        return parent::addTransaction($transactions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTransaction(\Sofid\AdminBundle\Entity\Transaction $transactions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTransaction', array($transactions));

        return parent::removeTransaction($transactions);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactions', array());

        return parent::getTransactions();
    }

    /**
     * {@inheritDoc}
     */
    public function addQuestion(\Sofid\PoolBundle\Entity\Question $questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addQuestion', array($questions));

        return parent::addQuestion($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function removeQuestion(\Sofid\PoolBundle\Entity\Question $questions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeQuestion', array($questions));

        return parent::removeQuestion($questions);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuestions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuestions', array());

        return parent::getQuestions();
    }

    /**
     * {@inheritDoc}
     */
    public function setPicture($picture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPicture', array($picture));

        return parent::setPicture($picture);
    }

    /**
     * {@inheritDoc}
     */
    public function getPicture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPicture', array());

        return parent::getPicture();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage(\Symfony\Component\HttpFoundation\File\UploadedFile $image = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', array($image));

        return parent::setImage($image);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', array());

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function getAbsolutePath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbsolutePath', array());

        return parent::getAbsolutePath();
    }

    /**
     * {@inheritDoc}
     */
    public function getWebPath()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebPath', array());

        return parent::getWebPath();
    }

    /**
     * {@inheritDoc}
     */
    public function preUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'preUpload', array());

        return parent::preUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function upload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'upload', array());

        return parent::upload();
    }

    /**
     * {@inheritDoc}
     */
    public function removeUpload()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUpload', array());

        return parent::removeUpload();
    }

    /**
     * {@inheritDoc}
     */
    public function setFirstname($firstname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFirstname', array($firstname));

        return parent::setFirstname($firstname);
    }

    /**
     * {@inheritDoc}
     */
    public function getFirstname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFirstname', array());

        return parent::getFirstname();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastname($lastname)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastname', array($lastname));

        return parent::setLastname($lastname);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastname()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastname', array());

        return parent::getLastname();
    }

    /**
     * {@inheritDoc}
     */
    public function setClient($client)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setClient', array($client));

        return parent::setClient($client);
    }

    /**
     * {@inheritDoc}
     */
    public function getClient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getClient', array());

        return parent::getClient();
    }

    /**
     * {@inheritDoc}
     */
    public function setSms($sms)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSms', array($sms));

        return parent::setSms($sms);
    }

    /**
     * {@inheritDoc}
     */
    public function getSms()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSms', array());

        return parent::getSms();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketMoyen($ticketMoyen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketMoyen', array($ticketMoyen));

        return parent::setTicketMoyen($ticketMoyen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketEphemMoyen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketEphemMoyen', array());

        return parent::getTicketEphemMoyen();
    }

    /**
     * {@inheritDoc}
     */
    public function setTicketEphemMoyen($ticketEphemMoyen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTicketEphemMoyen', array($ticketEphemMoyen));

        return parent::setTicketEphemMoyen($ticketEphemMoyen);
    }

    /**
     * {@inheritDoc}
     */
    public function getTicketMoyen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTicketMoyen', array());

        return parent::getTicketMoyen();
    }

    /**
     * {@inheritDoc}
     */
    public function setWebsite($website)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWebsite', array($website));

        return parent::setWebsite($website);
    }

    /**
     * {@inheritDoc}
     */
    public function getWebsite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWebsite', array());

        return parent::getWebsite();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacebookPage($facebookPage)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacebookPage', array($facebookPage));

        return parent::setFacebookPage($facebookPage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacebookPage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacebookPage', array());

        return parent::getFacebookPage();
    }

    /**
     * {@inheritDoc}
     */
    public function setGender($gender)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGender', array($gender));

        return parent::setGender($gender);
    }

    /**
     * {@inheritDoc}
     */
    public function getGender()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGender', array());

        return parent::getGender();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhone($phone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhone', array($phone));

        return parent::setPhone($phone);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhone', array());

        return parent::getPhone();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateOfBirth($dateOfBirth)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateOfBirth', array($dateOfBirth));

        return parent::setDateOfBirth($dateOfBirth);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateOfBirth()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateOfBirth', array());

        return parent::getDateOfBirth();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory($category)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', array($category));

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', array());

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function getEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEditable', array());

        return parent::getEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimitpoints1($limitpoints1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimitpoints1', array($limitpoints1));

        return parent::setLimitpoints1($limitpoints1);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimitpoints1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimitpoints1', array());

        return parent::getLimitpoints1();
    }

    /**
     * {@inheritDoc}
     */
    public function setLimitpoints2($limitpoints2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLimitpoints2', array($limitpoints2));

        return parent::setLimitpoints2($limitpoints2);
    }

    /**
     * {@inheritDoc}
     */
    public function getLimitpoints2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLimitpoints2', array());

        return parent::getLimitpoints2();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessageManualPointsScreen($messageManualPointsScreen)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessageManualPointsScreen', array($messageManualPointsScreen));

        return parent::setMessageManualPointsScreen($messageManualPointsScreen);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessageManualPointsScreen()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessageManualPointsScreen', array());

        return parent::getMessageManualPointsScreen();
    }

    /**
     * {@inheritDoc}
     */
    public function setDisplayEditable($displayEditable)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDisplayEditable', array($displayEditable));

        return parent::setDisplayEditable($displayEditable);
    }

    /**
     * {@inheritDoc}
     */
    public function getDisplayEditable()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDisplayEditable', array());

        return parent::getDisplayEditable();
    }

    /**
     * {@inheritDoc}
     */
    public function setExportOption($exportOption)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExportOption', array($exportOption));

        return parent::setExportOption($exportOption);
    }

    /**
     * {@inheritDoc}
     */
    public function getExportOption()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExportOption', array());

        return parent::getExportOption();
    }

    /**
     * {@inheritDoc}
     */
    public function setConversionValue($conversionValue)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConversionValue', array($conversionValue));

        return parent::setConversionValue($conversionValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getConversionValue()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConversionValue', array());

        return parent::getConversionValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', array($code));

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', array());

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function addRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRole', array($role));

        return parent::addRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function serialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'serialize', array());

        return parent::serialize();
    }

    /**
     * {@inheritDoc}
     */
    public function unserialize($serialized)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'unserialize', array($serialized));

        return parent::unserialize($serialized);
    }

    /**
     * {@inheritDoc}
     */
    public function eraseCredentials()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'eraseCredentials', array());

        return parent::eraseCredentials();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsername', array());

        return parent::getUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function getUsernameCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUsernameCanonical', array());

        return parent::getUsernameCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSalt', array());

        return parent::getSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmail', array());

        return parent::getEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailCanonical()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailCanonical', array());

        return parent::getEmailCanonical();
    }

    /**
     * {@inheritDoc}
     */
    public function getPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPassword', array());

        return parent::getPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getPlainPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPlainPassword', array());

        return parent::getPlainPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function getLastLogin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastLogin', array());

        return parent::getLastLogin();
    }

    /**
     * {@inheritDoc}
     */
    public function getConfirmationToken()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfirmationToken', array());

        return parent::getConfirmationToken();
    }

    /**
     * {@inheritDoc}
     */
    public function getRoles()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoles', array());

        return parent::getRoles();
    }

    /**
     * {@inheritDoc}
     */
    public function hasRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasRole', array($role));

        return parent::hasRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonExpired', array());

        return parent::isAccountNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isAccountNonLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isAccountNonLocked', array());

        return parent::isAccountNonLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsNonExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsNonExpired', array());

        return parent::isCredentialsNonExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isCredentialsExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isCredentialsExpired', array());

        return parent::isCredentialsExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isEnabled()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isEnabled', array());

        return parent::isEnabled();
    }

    /**
     * {@inheritDoc}
     */
    public function isExpired()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isExpired', array());

        return parent::isExpired();
    }

    /**
     * {@inheritDoc}
     */
    public function isLocked()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isLocked', array());

        return parent::isLocked();
    }

    /**
     * {@inheritDoc}
     */
    public function isSuperAdmin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isSuperAdmin', array());

        return parent::isSuperAdmin();
    }

    /**
     * {@inheritDoc}
     */
    public function isUser(\FOS\UserBundle\Model\UserInterface $user = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isUser', array($user));

        return parent::isUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRole', array($role));

        return parent::removeRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsername($username)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsername', array($username));

        return parent::setUsername($username);
    }

    /**
     * {@inheritDoc}
     */
    public function setUsernameCanonical($usernameCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUsernameCanonical', array($usernameCanonical));

        return parent::setUsernameCanonical($usernameCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpireAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpireAt', array($date));

        return parent::setCredentialsExpireAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setCredentialsExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCredentialsExpired', array($boolean));

        return parent::setCredentialsExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmail($email)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmail', array($email));

        return parent::setEmail($email);
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailCanonical($emailCanonical)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailCanonical', array($emailCanonical));

        return parent::setEmailCanonical($emailCanonical);
    }

    /**
     * {@inheritDoc}
     */
    public function setEnabled($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEnabled', array($boolean));

        return parent::setEnabled($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpired($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpired', array($boolean));

        return parent::setExpired($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setExpiresAt(\DateTime $date)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExpiresAt', array($date));

        return parent::setExpiresAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function setPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPassword', array($password));

        return parent::setPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperAdmin($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperAdmin', array($boolean));

        return parent::setSuperAdmin($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setPlainPassword($password)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPlainPassword', array($password));

        return parent::setPlainPassword($password);
    }

    /**
     * {@inheritDoc}
     */
    public function setLastLogin(\DateTime $time)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastLogin', array($time));

        return parent::setLastLogin($time);
    }

    /**
     * {@inheritDoc}
     */
    public function setLocked($boolean)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocked', array($boolean));

        return parent::setLocked($boolean);
    }

    /**
     * {@inheritDoc}
     */
    public function setConfirmationToken($confirmationToken)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfirmationToken', array($confirmationToken));

        return parent::setConfirmationToken($confirmationToken);
    }

    /**
     * {@inheritDoc}
     */
    public function setPasswordRequestedAt(\DateTime $date = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPasswordRequestedAt', array($date));

        return parent::setPasswordRequestedAt($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getPasswordRequestedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPasswordRequestedAt', array());

        return parent::getPasswordRequestedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function isPasswordRequestNonExpired($ttl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isPasswordRequestNonExpired', array($ttl));

        return parent::isPasswordRequestNonExpired($ttl);
    }

    /**
     * {@inheritDoc}
     */
    public function setRoles(array $roles)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoles', array($roles));

        return parent::setRoles($roles);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroups()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroups', array());

        return parent::getGroups();
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupNames()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupNames', array());

        return parent::getGroupNames();
    }

    /**
     * {@inheritDoc}
     */
    public function hasGroup($name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'hasGroup', array($name));

        return parent::hasGroup($name);
    }

    /**
     * {@inheritDoc}
     */
    public function addGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addGroup', array($group));

        return parent::addGroup($group);
    }

    /**
     * {@inheritDoc}
     */
    public function removeGroup(\FOS\UserBundle\Model\GroupInterface $group)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeGroup', array($group));

        return parent::removeGroup($group);
    }

}
