<?php

namespace Sofid\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends EntityRepository
{
	/**
	 * returns count paliers
	 */
	public function getPaliersCount($id) {
	
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT count(t) FROM SofidAdminBundle:Transaction t WHERE t.palier IS NOT NULL AND t.commercant = ?1');
		$query->setParameter(1, $id);
		return $query->getSingleScalarResult();
	}
	
	/**
	 * returns count offres
	 */
	public function getOffresCount($id) {
	
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT count(t) FROM SofidAdminBundle:Transaction t WHERE t.offre IS NOT NULL AND t.commercant = ?1');
		$query->setParameter(1, $id);
		return $query->getSingleScalarResult();
	}
}
