<?php

namespace Sofid\AdminBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
	/**
	 * Getting last gain within 5 minutes
	 */
	public function getLastGain($timestamp, $id) {
		
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT g.id, g.shared FROM SofidAdminBundle:Gain g WHERE g.timestamp >= ?1 AND g.user = ?2 ORDER BY g.timestamp DESC');
		$query->setParameter(1, $timestamp);
		$query->setParameter(2, $id);
		$query->setMaxResults(1);
		return $query->getSingleResult();
	}
        
        /**
	 * Find user by email or telephone
	 */
	public function findOneByEmailOrPhone($email, $telephone) {
		
		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT u FROM SofidAdminBundle:User u WHERE u.email = ?1 OR u.telephone = ?2');
		$query->setParameter(1, $email);
		$query->setParameter(2, $telephone);
		return $query->getOneOrNullResult();
	}
}
