imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata_user.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: "%kernel.debug%"
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  fr
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%
        types:
            json: Sonata\Doctrine\Types\JsonType

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        
services:
    export:
        class: Sofid\CommercantBundle\Services\Export
        arguments: [@service_container]
    card.encoder:
        class: Sofid\AdminBundle\Listener\CardEncoder
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    code.encoder:
            class: Sofid\UserBundle\Listener\CodeEncoder
            tags:
                - { name: doctrine.event_listener, event: postPersist }
    commercant.client:
        class: Sofid\AdminBundle\Listener\CommercantClient
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    sonata.user.admin.group:
      abstract: true
      public: false
    
    sonata.user.admin.user:
      abstract: true
      public: false
    nexmo_sms_manager:
        class: Sofid\UserBundle\Helper\Nexmo
        arguments: [@service_container]

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_advanced_encoder:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
        sofid_encoder:
            id: sofid.sofid_encoder
    
fos_user:
    db_driver:      orm # can be orm or odm
    firewall_name:  main
    user_class:     Sofid\UserBundle\Entity\Commercant
    profile:
        form:
            type: sofid_edit_commercant
        
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]

        sonata.block.service.text:
        sonata.block.service.rss:
        sonata.block.service.qrcode: ~

        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
        
stof_doctrine_extensions:
    default_locale: fr_FR
    orm:
        default:
            tree: true
            timestampable: true # not needed: listeners are not enabled by default
            
sonata_admin:
    title:      SoFID
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig

        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig

    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: left, type: sonata.block.service.qrcode}