parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     sofid_1
    database_user:     root
    database_password: 

    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: ~
    mailer_password: ~
    locale: en
    secret: 6a955ac31d3cb68edbeec37ce69f39ec3776668a
