pool:
    resource: "@PoolBundle/Resources/config/routing.yml"
    prefix:   /pool

sofid_user:
    resource: "@SofidUserBundle/Resources/config/routing.yml"
    prefix:   /

#sofid_admin:
#    resource: "@SofidAdminBundle/Resources/config/routing.xml"
#    prefix:   /

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile
    
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
    
sofid_admin:
    resource: "@SofidAdminBundle/Resources/config/routing.yml"
    
sofid_commercant:
    resource: "@SofidCommercantBundle/Resources/config/routing.yml"
    prefix:   /commercant

sofid_fidele:
    resource: "@SofidFideleBundle/Resources/config/routing.yml"
    prefix:   /fidele