<?php

namespace Sofid\FideleBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class FideleController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sofid\FideleBundle\Controller\FideleController();
        return $instance;
    }
}
