<?php

namespace Sofid\UserBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class CommercantController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sofid\UserBundle\Controller\CommercantController();
        return $instance;
    }
}
