<?php

namespace Sofid\PoolBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ApiController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sofid\PoolBundle\Controller\ApiController();
        return $instance;
    }
}
