<?php

namespace Proxies\__CG__\Sofid\AdminBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Palier extends \Sofid\AdminBundle\Entity\Palier implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'nbPointPalier', 'numPalier', 'recompense', 'commercant', 'transactions');
        }

        return array('__isInitialized__', 'id', 'nbPointPalier', 'numPalier', 'recompense', 'commercant', 'transactions');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Palier $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPointPalier($nbPointPalier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPointPalier', array($nbPointPalier));

        return parent::setNbPointPalier($nbPointPalier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPointPalier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPointPalier', array());

        return parent::getNbPointPalier();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumPalier($numPalier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumPalier', array($numPalier));

        return parent::setNumPalier($numPalier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumPalier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumPalier', array());

        return parent::getNumPalier();
    }

    /**
     * {@inheritDoc}
     */
    public function setRecompense($recompense)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRecompense', array($recompense));

        return parent::setRecompense($recompense);
    }

    /**
     * {@inheritDoc}
     */
    public function getRecompense()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRecompense', array());

        return parent::getRecompense();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommercant(\Sofid\UserBundle\Entity\Commercant $commercant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommercant', array($commercant));

        return parent::setCommercant($commercant);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommercant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommercant', array());

        return parent::getCommercant();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

}
