<?php

namespace Sofid\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommercantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommercantRepository extends EntityRepository
{
	/**
	 * Getting all commercants
	 */
	public function getAllCommercants($pageId) {

		$em = $this->getEntityManager();
		$query = $em->createQuery('SELECT c.id, c.entreprise, c.adresse, c.codePostal, c.ville, c.picture FROM SofidUserBundle:Commercant c')
                    ->setMaxResults(10)
                    ->setFirstResult(10 * $pageId);

		return $query->getArrayResult();
	}
}
